### ISSUE TITLE
minor issues when building installer images

### ISSUE THREAD

**Issue by linsun** [istio/installer#117]
1. need to build istioctl linux binary first when running `make docker.istio-builder`

2. need to create the dir first `${TMPDIR}/bin/` for the cp command to work to copy istioctl over.

**Comment by linsun** [comment]
@ericvn since you have been working on this, can you help?

**Comment by ericvn** [comment]
@linsun I'll look into this. I thought this worked for me last week with the Makefile (both those items should have been done ), but there were some last minutes changes.
