### ISSUE TITLE
Add PDB to injector

### ISSUE THREAD

**Issue by howardjohn** [istio/installer#133]
John Howard [4:05 PM]
Does anyone have any context as to why we don't have PodDisruptionBudget for sidecar injector? It seems like a critical component given that pods cannot be created without it? We have PDBs for almost everything else so I was wondering if it was explicitly excluded (edited) 

Steve Dake [4:13 PM]
not explicit
oversiight
feel free to fix :slightly_smiling_face:

**Comment by morvencao** [comment]
I think we can close this.
