### ISSUE TITLE
running make test locally failed

### ISSUE THREAD

**Issue by linsun** [istio/installer#135]
with 2 pods not able to reach running: (after excluding the mixer redis testing)

```
root@test-control-plane:/Users/linsun/go/src/istio.io/installer# kubectl describe pod nginx-default-http-backend-84bdb65549-nwwkd  -n simple-strict
  Normal   Pulled     14m (x3 over 16m)   kubelet, test-control-plane  Container image "gcr.io/google_containers/defaultbackend:1.4" already present on machine
  Warning  Unhealthy  10m (x7 over 12m)   kubelet, test-control-plane  (combined from similar events): Liveness probe failed: Get http://10.32.0.24:8080/healthz: read tcp 10.32.0.1:60862->10.32.0.24:8080: read: connection reset by peer
  Warning  BackOff    70s (x39 over 10m)  kubelet, test-control-plane  Back-off restarting failed container
```

```
kubectl describe pod prometheus-operator-5566546995-g8tsc
  Normal   Pulled     16m                  kubelet, test-control-plane  Container image "quay.io/coreos/prometheus-operator:v0.29.0" already present on machine
  Warning  BackOff    16m (x2 over 16m)    kubelet, test-control-plane  Back-off restarting failed container
  Warning  Unhealthy  98s (x448 over 16m)  kubelet, test-control-plane  Readiness probe failed: HTTP probe failed with statuscode: 503
```

**Comment by morvencao** [comment]
CircleCI workflow is working now, but the steps are fixed. 
So what's you local test step? Seems that you should run the `run-prometheus-operator-config-test` target.

**Comment by ericvn** [comment]
You also need https://github.com/istio/installer/pull/137 before `make test` will run to fix this.

**Comment by ericvn** [comment]
Note that the prometheus operator test was never added in the CI and the CI does not do a `make test`. Once PR 137 is merged, the CI can be updated to do one or both.

**Comment by ericvn** [comment]
Well, #137 should have fixed this but the prometheus operator has a half release which is causing a new failure: https://github.com/coreos/prometheus-operator/issues/2598. Seems they have a tentative plan to get that fully published on Monday.

**Comment by ericvn** [comment]
The prometheus-operator should now be fixed. Running a `make test` to confirm things work, or maybe more likely, what is broken next ;) .

**Comment by ericvn** [comment]
`make test` now passes so closing this issue. 

We still need to get the prometheus-operator added into the CI pipeline.
