### ISSUE TITLE
What is the roadmap for Istio installation?

### ISSUE THREAD

**Issue by andrecastro** [istio/installer#175]
Hello guys,

I would like to understand what is the roadmap of how to deploy Istio and what is the tool you seek to use/maintain in future versions.

My task is to evaluate what are the possible ways to install Istio in my k8s cluster, and today I see 3 options:

* Use helm chart
* Use istio-operator from banzai cloud
* Use this installer

but I would like to understand what you guys have in mind. Some questions I have:

* Are going to deprecate the usage of helm chart?
* Are going to create a new Istio Operator?
* What exactly this installer has in advantage of the helm chart?

**Comment by fpesce** [comment]
Issue moved to [istio/istio #14116](https://github.com/istio/istio/issues/14116) via [**ZenHub**](https://www.zenhub.com/)
